# Site settings
title: Learn Co Blog
header-img: img/home-bg.png
email: lekan.nicholson@gmail.com
copyright_name: lekan20
description: > # this means to ignore newlines until "baseurl:"
  Learn Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: kanle20
github_username:  lekan20
learn_profile: lekan20
email_username: lekan.nicholson@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
